// This file is auto-generated by `web/scripts/generate-export-columns.mjs`.
// Do not edit by hand. Regenerate after DB type generation.

import type { Database } from '@/lib/supabase/database.types'

export type ExportTableName = keyof Database['public']['Tables']

export const EXPORT_COLUMNS: Record<ExportTableName, readonly string[]> = {
  administration_events: ['cost_usd', 'created_at', 'cycle_instance_id', 'deleted_at', 'dose_mass_mg', 'dose_volume_ml', 'eff_cns_p05_mg', 'eff_cns_p50_mg', 'eff_cns_p95_mg', 'eff_systemic_p05_mg', 'eff_systemic_p50_mg', 'eff_systemic_p95_mg', 'formulation_id', 'id', 'input_kind', 'input_text', 'input_unit', 'input_value', 'mc_n', 'mc_seed', 'model_snapshot', 'notes', 'tags', 'ts', 'updated_at', 'user_id', 'vial_id'],
  bioavailability_specs: ['base_fraction_dist_id', 'compartment', 'created_at', 'deleted_at', 'evidence_source_id', 'id', 'notes', 'route_id', 'substance_id', 'updated_at', 'user_id'],
  component_modifier_specs: ['compartment', 'created_at', 'deleted_at', 'formulation_component_id', 'id', 'multiplier_dist_id', 'notes', 'updated_at', 'user_id'],
  cycle_instances: ['created_at', 'cycle_number', 'deleted_at', 'end_ts', 'goal', 'id', 'notes', 'start_ts', 'status', 'substance_id', 'updated_at', 'user_id'],
  cycle_rules: ['auto_start_first_cycle', 'created_at', 'deleted_at', 'gap_days_to_suggest_new_cycle', 'id', 'notes', 'substance_id', 'updated_at', 'user_id'],
  device_calibrations: ['created_at', 'deleted_at', 'device_id', 'id', 'notes', 'route_id', 'unit_label', 'updated_at', 'user_id', 'volume_ml_per_unit_dist_id'],
  devices: ['created_at', 'default_unit', 'deleted_at', 'device_kind', 'id', 'name', 'notes', 'updated_at', 'user_id'],
  distributions: ['created_at', 'deleted_at', 'dist_type', 'evidence_summary', 'id', 'max_value', 'min_value', 'name', 'p1', 'p2', 'p3', 'quality_score', 'units', 'updated_at', 'user_id', 'value_type'],
  event_revisions: ['created_at', 'event_id', 'id', 'new_values', 'old_values', 'reason', 'revised_at', 'user_id'],
  evidence_sources: ['citation', 'created_at', 'deleted_at', 'id', 'notes', 'source_type', 'updated_at', 'user_id'],
  formulation_components: ['component_name', 'created_at', 'deleted_at', 'formulation_id', 'id', 'modifier_dist_id', 'notes', 'role', 'updated_at', 'user_id'],
  formulation_modifier_specs: ['compartment', 'created_at', 'deleted_at', 'formulation_id', 'id', 'multiplier_dist_id', 'notes', 'updated_at', 'user_id'],
  formulations: ['created_at', 'deleted_at', 'device_id', 'id', 'is_default_for_route', 'name', 'notes', 'route_id', 'substance_id', 'updated_at', 'user_id'],
  order_items: ['created_at', 'deleted_at', 'expected_vials', 'formulation_id', 'id', 'notes', 'order_id', 'price_total_usd', 'qty', 'substance_id', 'unit_label', 'updated_at', 'user_id'],
  orders: ['created_at', 'deleted_at', 'id', 'notes', 'ordered_at', 'shipping_cost_usd', 'total_cost_usd', 'tracking_code', 'updated_at', 'user_id', 'vendor_id'],
  profiles: ['created_at', 'cycle_gap_default_days', 'default_mass_unit', 'default_simulation_n', 'default_volume_unit', 'timezone', 'updated_at', 'user_id'],
  routes: ['created_at', 'default_input_kind', 'default_input_unit', 'deleted_at', 'id', 'name', 'notes', 'supports_device_calibration', 'updated_at', 'user_id'],
  substance_aliases: ['alias', 'created_at', 'deleted_at', 'id', 'substance_id', 'updated_at', 'user_id'],
  substance_recommendations: ['category', 'created_at', 'deleted_at', 'evidence_source_id', 'id', 'max_value', 'min_value', 'notes', 'route_id', 'substance_id', 'unit', 'updated_at', 'user_id'],
  substances: ['canonical_name', 'created_at', 'deleted_at', 'display_name', 'family', 'id', 'notes', 'target_compartment_default', 'updated_at', 'user_id'],
  vendors: ['created_at', 'deleted_at', 'id', 'name', 'notes', 'updated_at', 'user_id'],
  vials: ['closed_at', 'concentration_mg_per_ml', 'content_mass_unit', 'content_mass_value', 'cost_usd', 'created_at', 'deleted_at', 'formulation_id', 'id', 'lot', 'notes', 'opened_at', 'order_item_id', 'received_at', 'status', 'substance_id', 'total_volume_unit', 'total_volume_value', 'updated_at', 'user_id', 'volume_ml_per_unit_override_dist_id'],
}
